HEIGHT = 800
WIDTH = 600

NUMBER_OF_TESTS = 100
ANSWERS = ['A', 'B', 'A', 'D', 'C', 'F', 'E', 'A', 'C', 'A', 'D', 'A', 'E', 'A', 'A', 'F', 'A', 'B', 'B', 'C']
EXPECTED_CORRECT_ANSWERS = [8, 5, 1, 2, 4, 4]

RED_PIXEL_THRESHHOLD = 30

NUMBER_OF_QUESTIONS = 20
NUMBER_OF_ANSWERS = 6
NUMBER_OF_ERROR_ANSWERS = 3

PHOTO_LEFT = 160
PHOTO_TOP = 190
PHOTO_RIGHT = WIDTH - 70
PHOTO_BOTTOM = HEIGHT - 290

ADJUST_ANSWERS_LEFT = 0
ADJUST_ANSWERS_TOP = 0
ADJUST_ANSWERS_RIGHT = 190
ADJUST_ANSWERS_BOTTOM = 0

ADJUST_ERROR_LEFT = 170
ADJUST_ERROR_TOP = 0
ADJUST_ERROR_RIGHT = 150
ADJUST_ERROR_BOTTOM = 0

ADJUST_ERROR_ANSWERS_LEFT = 90
ADJUST_ERROR_ANSWERS_TOP = 2
ADJUST_ERROR_ANSWERS_RIGHT = 9
ADJUST_ERROR_ANSWERS_BOTTOM = 8

word_dict = {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L', 12: 'M',
             13: 'N', 14: 'O', 15: 'P', 16: 'Q', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'X', 24: 'Y',
             25: 'Z'}